# Basic
title: createstone
subtitle: createstone's blog
welcome_message: welcome to my blog
description: this is the recode of my share
# creator: <a href="http://onev.cat">@onevcat</a>

url: "https://createstone.github.io/"
baseurl: ""
permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 博客 
    url: 'https://www.cnblogs.com/zhen-sun/'

# Navigation buttons in the front page.
nav:
    - {title: 简历, description: 个人简历, url: 'http://createstone.github.io/myprofile'}
    # - {title: Another Button, description: A button, url: 'http://example.com'} 
# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: CreateStone
    # duoshuo:

# Social
social:
    # weibo: onevcat
    github: createStone
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: 1165248955@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
